[32m2024-07-09 16:14:09 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8ee53091-4fbc-4c81-b5a4-84b966d9275a - 13737 - LOGS_CAPTURED - Started capturing logs in process (pid: 13737).
[32m2024-07-09 16:14:09 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 8ee53091-4fbc-4c81-b5a4-84b966d9275a - 13737 - EXT_SLS_MOTORCYCLES_INIT - STEP_START - Started execution of step "EXT_SLS_MOTORCYCLES_INIT".
[32m2024-07-09 16:14:09 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - 8ee53091-4fbc-4c81-b5a4-84b966d9275a - EXT_SLS_MOTORCYCLES_INIT - Executing query: 
        CALL SPEEDSHOP_PROC.EXT_SLS_MOTORCYCLES_INIT();
    
[32m2024-07-09 16:14:10 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 8ee53091-4fbc-4c81-b5a4-84b966d9275a - 13737 - EXT_SLS_MOTORCYCLES_INIT - STEP_FAILURE - Execution of step "EXT_SLS_MOTORCYCLES_INIT" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "EXT_SLS_MOTORCYCLES_INIT"::

snowflake.connector.errors.ProgrammingError: 002003 (02000): Execution error in store procedure EXT_SLS_MOTORCYCLES_INIT:
SQL compilation error:
Schema 'VS_AWS_DB.SALES' does not exist or not authorized.
At Statement.execute, line 116 position 5

Stack Trace:
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/Documents/GitHub/quickstart-snowflake-fix-fast-deploys/quickstart_snowflake/assets/init_sales.py", line 120, in EXT_SLS_MOTORCYCLES_INIT
    cursor.execute(query)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/bryanmull/miniforge3/envs/dagsteru/lib/python3.11/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
[0m
